# -*- coding: utf-8 -*-
"""CropDataVisualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c6FTiiUR4yV1ixbphR_oJzACfpcE0D1O
"""

import pandas as pd
import matplotlib.pyplot as plt

data = {
    'Year': [2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023],
    'Total Acreage Per Year': [9729930.94, 11380712.17, 11323466.27, 9581984.78, 11509326.86, 11500767.07, 11456038.64, 11351439.4335, 9763853.0401, 11405404.1713, 11474406.9227, 10688382.674, 11402917.0858, 11419888.3101, 11366881.6122, 11393587.6152]
}

df = pd.DataFrame(data)

plt.figure(figsize=(10, 5))
plt.plot(df['Year'], df['Total Acreage Per Year'], marker='o')
plt.title('Total Crop Acreage by Year')
plt.xlabel('Year')
plt.ylabel('Acreage (in thousands)')
plt.grid(True)
plt.show()

# Load the Excel file into a Pandas DataFrame
df = pd.read_excel("precipitation.xlsx")

# Print the DataFrame columns
# print(df.columns)

# Extract year from the date in "Date" column
df['Year'] = pd.DatetimeIndex(df['Time']).year

filtered_df = df[df['Year'].between(2008, 2023)]

# Group by year and sum precipitation values
yearly_precipitation = filtered_df.groupby('Year')['Precipatation'].sum()

# Display or save the yearly total precipitation
print(yearly_precipitation)

yearly_precipitation.plot(kind='line', figsize=(10, 6))
plt.title('Yearly Precipitation (2008-2023)')
plt.xlabel('Year')
plt.ylabel('Total Precipitation (mm)')
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.tight_layout()
plt.grid(True)
plt.show()

# Crop acreage data
crop_data = {
    'Year': [2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023],
    'Total Acreage Per Year': [9729930.94, 11380712.17, 11323466.27, 9581984.78, 11509326.86, 11500767.07, 11456038.64, 11351439.4335, 9763853.0401, 11405404.1713, 11474406.9227, 10688382.674, 11402917.0858, 11419888.3101, 11366881.6122, 11393587.6152]
}

crop_df = pd.DataFrame(crop_data)

# Precipitation data
precipitation_df = pd.read_excel("precipitation.xlsx")
precipitation_df['Year'] = pd.DatetimeIndex(precipitation_df['Time']).year
filtered_precipitation_df = precipitation_df[precipitation_df['Year'].between(2008, 2023)]
yearly_precipitation = filtered_precipitation_df.groupby('Year')['Precipatation'].sum()

# Plotting
fig, ax1 = plt.subplots(figsize=(10, 6))

# Plot crop acreage
color = 'tab:red'
ax1.set_xlabel('Year')
ax1.set_ylabel('Crop Acreage (in thousands)', color=color)
ax1.plot(crop_df['Year'], crop_df['Total Acreage Per Year'], color=color, marker='o', label='Crop Acreage')
ax1.tick_params(axis='y', labelcolor=color)

# Create a second y-axis for precipitation
ax2 = ax1.twinx()
color = 'tab:blue'
ax2.set_ylabel('Total Precipitation (mm)', color=color)
ax2.plot(yearly_precipitation.index, yearly_precipitation.values, color=color, marker='s', label='Precipitation')
ax2.tick_params(axis='y', labelcolor=color)

# Title and legend
plt.title('Crop Acreage and Precipitation (2008-2023)')
fig.tight_layout()
fig.legend(loc='upper left')

plt.show()